### ISSUE TITLE
He can't find some posters for movies

### ISSUE THREAD

**Issue by Machou** [xbmc/metadata.themoviedb.org.python#161]
Hello,

For some time, when I search for movies or series, the addon does not find the poster. But it is there.

For example : Smurfs: The Lost Village

![image](https://user-images.githubusercontent.com/1043650/204553592-99c9ab5b-f10f-41e1-9369-50d7debfe342.jpeg)

Maybe there is a problem with TMDB?

Sincerely

**Comment by KarellenX** [comment]
Can you delete that movie from your library and capture the rescraping in a debuglog and post the debug log. 
Thanks.

**Comment by Machou** [comment]
> Can you delete that movie from your library and capture the rescraping in a debuglog and post the debug log. 
> 
> Thanks.

Where is the debug log ?

**Comment by KarellenX** [comment]
Here... https://kodi.wiki/view/Log_file/Easy

**Comment by Machou** [comment]
I have delete the movie, install Kodi Logfile Uploader, and re-scan the movie.

Here log : https://paste.kodi.tv/iqewijakox

30 November 2022 - 3:35pm / 3:38pm

**Comment by KarellenX** [comment]
In future, please start all your reports on the forum. If there is a bug, we will ask you to create a report here.

The error on line 7343 is...
`CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://assets.fanart.tv/fanart/movies/41513/movieposter/the-smurfs-567026da6f15e.jpg`

This means that the TCP connection fails to the given host/port. Maybe you are using a Proxy or a VPN? The issue seems to be the configuration on your android box, which I cannot help you with. Sorry.

**Comment by Machou** [comment]
> In future, please start all your reports on the forum. If there is a bug, we will ask you to create a report here.
> 
> 
> 
> The error on line 7343 is...
> 
> `CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://assets.fanart.tv/fanart/movies/41513/movieposter/the-smurfs-567026da6f15e.jpg`
> 
> 
> 
> This means that the TCP connection fails to the given host/port. Maybe you are using a Proxy or a VPN? The issue seems to be the configuration on your android box, which I cannot help you with. Sorry.
> 
> 

I have restart my box + Kodi, rescrape and all is good.
